//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCodingASPNET_QE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMaster
    {
        public int CarMasterId { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public int YearMade { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    }
}
